---
- name: Install dependencies
  ansible.builtin.package:
    name: curl
    state: present

- name: Download Wazuh agent repo
  ansible.builtin.shell: |
    curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | sudo apt-key add -
    echo "deb https://packages.wazuh.com/4.x/apt stable main" | sudo tee /etc/apt/sources.list.d/wazuh.list
  args:
    executable: /bin/bash

- name: Install Wazuh agent
  ansible.builtin.package:
    name: wazuh-agent
    state: present
    update_cache: yes

- name: Deploy wazuh agent config
  ansible.builtin.template:
    src: ossec.conf.j2
    dest: /var/ossec/etc/ossec.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable and start Wazuh agent
  ansible.builtin.service:
    name: wazuh-agent
    state: started
    enabled: yes
